# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: hackathon-spaceship-python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./hackathon-spaceship-python/hackathon-spaceship-python/
    steps:
    - uses: actions/checkout@v3
    - name: Experiment
      run: |
        pwd 
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install poetry
      run: |
        python -m pip install poetry==1.4.2
    - name: Install dependencies
      run: |
        python -m poetry install
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest
